env:
  browser: true
  es2021: true
  node: true
extends:
  - '@nuxtjs/eslint-config-typescript'
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - eslint:recommended
  - '@vue/typescript/recommended'
  - '@vue/prettier'
overrides: []
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'

rules:
  {
    'no-irregular-whitespace': 0,
    '@typescript-eslint/no-unused-vars': 'off',
    'camelcase': 'off',
    'vue/multi-word-component-names': 'off',
    'vue/no-multiple-template-root': 0,
    'vue/no-v-html': 'off',
  }
